IBM/watson-discovery-ui

server/index.js
src/layouts/default.js

Was getting additional request from browser to render favicon.ico
See - https://stackoverflow.com/questions/1321878/how-to-prevent-favicon-ico-requests/38917888?noredirect=1#comment77478543_38917888

fixed problem with browser requests for favicon.ico

---

public/css/application.css
server/index.js
src/Entities/index.js
src/SearchField/index.js
src/main.js

- entities remembering their state, even if their count changes
- search box with blank entry no retrieves all records
- commented entities class code
- entities are all cleared out if new search string is entered

entities and serach working

---

server/index.js
src/Categories/index.js
src/Entities/index.js
src/FilterBase/FilterContainer/index.js
src/FilterBase/FilterItem/index.js
src/main.js
src/utils.js

Now Entities and Categories extend FilterContainer.

refactored with new filterItem and filterContainer

---

server/index.js
server/query-builder.js
src/main.js

use '[]' to get each aggregation separately

fixed search aggregations

---

src/SentimentChart/index.js

make sure percentages add up to 100

sentiment chart percentages issue

---

server/index.js
server/query-builder.js
src/Matches/index.js
src/PaginationMenu/index.js
src/main.js

- added 'num matches' to title
- pagination menu added but not functional

added pagination menu

---

src/PaginationMenu/index.js
src/main.js

- listens for changes to 'numMatches' so we can redraw the pagination menu accordingly
- removes menu if number of matches is one page
- handles 'next' and 'prev' menu items being selected

fixed pagination issues

---

README.md
manifest.yml
package-lock.json
package.json
public/js/bundle.js
server/express.js
server/query-builder.js

Also changed '-_score' to '-score' in queryBuilder
Something in watson api must have changed, because old way suddently started failing with 
"Error: [_score] unknown field [unmapped_type], parser not found"

package name changes

---

README.md
public/css/application.css
server/index.js
server/query-builder.js
src/FilterBase/FilterItem/index.js
src/SearchField/index.js
src/main.js
src/utils.js

- added new checkboxes to search bar
- pass these values to queryBuilder for call to discovery service
- refactored the building of the search params for queryBuilder
- update README

added optional params to search bar

---

README.md
app.js
manifest.yml
server/index.js
server/query-builder.js
src/KeywordsFilter/index.js
src/SentimentChart/index.js
src/TagCloudRegion/index.js
src/index.js
src/main.js
src/utils.js

- updated query to retrieve key words
- added keyword filter object
- added keyword items to tag cloud
- added keyword items to sentiment chart

added keyword filter to query and UI

---

server/index.js
server/query-builder-trending.js
server/watson-discovery-service.js
src/SentimentChart/index.js
src/TrendChart/index.js
src/main.js
src/utils.js

- query is now build by user action
- made the text 'Term' a variable in utils, in case we want to change it all dropdown lists

trending improvements

---

server/index.js
server/query-builder-trending.js
server/query-builder.js
src/Matches/index.js
src/SentimentChart/index.js
src/TrendChart/index.js
src/main.js

- bumped up discovery version
- removed 'score' from query, no longer supported in disco (moved to enriched_metadata?)

trend chart fully functional

---

server/index.js
src/TrendChart/index.js
src/main.js
src/utils.js

- show breakdown of review sentiment in header

misc ui changes

---

src/Matches/index.js
src/SearchField/index.js
src/TrendChart/index.js
src/main.js

added title to main panel

---

src/SentimentChart/index.js
src/TrendChart/index.js
src/main.js
src/utils.js

- sentiment chart will use "All Terms"
- trending chart will use "Select Term"

update term names

---

public/css/application.css
server/index.js
server/query-builder-trending.js
server/query-builder.js
src/main.js

- error when url contains search string on initial start up - needed to add additional default params
- center pagination window

handle initial search from url

---

public/css/application.css
src/SentimentChart/index.js
src/TrendChart/index.js
src/main.js

- added space between drop down menus for both sentiment and trending chart panels

css for term dropdown

---

public/css/application.css
server/index.js
server/query-builder-trending.js
server/query-builder.js
src/Matches/index.js
src/SearchField/index.js

- added passages to search params
- removed sort on date, default is score
- show score value with each item
- expanded width of search input field
- removed top margin from page

added passages search

---

package-lock.json
package.json
public/css/application.css
server/index.js
src/Matches/index.js
src/SentimentChart/index.js
src/main.js
src/utils.js

- add sorting drop down to top of matches list
- disco query now has a sort option

added sorting to matches list

---

DEVELOPING.md
README.md
package.json
server/express.js

- update readme
- add 'jest -u' option to package, so that 'npm test -u' will update snapshots
- updated DEVELOPING.md list of components

misc fixes

---

README.md
manifest.yml
server/index.js

- updated memory in manifest to 1024 to see if we can get past 'out of memory' issue
- upped the number of documents to process to 2000

update README and manifest

---

manifest.yml

manifest memory size

---

DEVELOPING.md
README.md
lib/utils.js
server/index.js
src/main.js

- if query by passages, only keep matches that have a corresponding passage
- fixed sort issue to keep track of internal sort keys and external sort keys (used for Discovery queries)
- update some documentation

fixed passages

---

MAINTAINERS.md

Duplicated word

---

README.md
lib/watson-discovery-setup.js
server/index.js

- now we can create the disco config file during setup, with makes the D2B experience much better.
- remove old manual instructions from README

create keyword extraction config

---

lib/utils.js
server/index.js
server/query-builder.js
src/EntityTypesFilter/index.js
src/SentimentChart/index.js
src/TagCloudRegion/index.js
src/TrendChart/index.js
src/main.js
test/__snapshots__/tagCloudRegion.test.js.snap
test/query-builder.test.js

To add 'entity types' as a new facet, we needed to do the following:
1) add as an aggregate to our disco query
2) added to filter options, tag cloud options, sentiment and trending chart options

added entity types as a new facet

---

DEVELOPING.md
README.md

- update README
- update DEVELOPING to add reference to new filter type

add link to video

---

manifest.yml

Reverts IBM/watson-discovery-ui#102

Revert "try memory fix"

---

lib/utils.js
lib/watson-discovery-setup.js
package-lock.json
src/Matches/index.js
test/__snapshots__/matches.test.js.snap

'mentions' are created by adding params to the discovery configuration. Note that this can only be done via the API, so users who run create their data collection manually will not get this feature.

now highlight entity mention keywords

---

lib/utils.js

need to handle case where discovery config already exists and was not created with entity "mentions" turned on

check for valid array

---

lib/utils.js
package-lock.json

added additional array bounds check.
closes #124

fix index error

---

lib/utils.js
package-lock.json
package.json
src/Matches/index.js

Thanks to @Lotti for this fix to hilite multiple entries returned by Disco.
Fixes #123

can now hilite multiple items returned by disco

---

package-lock.json
package.json

add package

---

doc/source/openshift.md

update openshift instructions

---

.travis.yml
lib/utils.js
lib/watson-discovery-setup.js
package-lock.json
package.json
server/disco-events.js
server/index.js
server/query-builder-trending.js
server/query-builder.js
src/CategoriesFilter/index.js
src/ConceptsFilter/index.js
src/EntitiesFilter/index.js
src/EntityTypesFilter/index.js
src/FilterBase/FilterContainer/index.js
src/KeywordsFilter/index.js
src/Matches/index.js
src/PaginationMenu/index.js
src/SearchField/index.js
src/SentimentChart/index.js
src/TagCloudRegion/index.js
src/TrendChart/index.js
src/main.js
test/disco-events.test.js
test/query-builder-trending.test.js
test/query-builder.test.js
test/tagCloudRegion.test.js

- upgrade ibm-watson
- upgrade node
- upgrade react

upgrade dependencies

---

doc/source/local.md
doc/source/openshift.md
env.sample

- key name in docs was incorrectly set to DISCOVERY_IAM_APIKEY

change docs to reflect key name DISCOVERY_APIKEY

---

.travis.yml
package-lock.json
package.json
src/main.js
test/__snapshots__/tagCloudRegion.test.js.snap

- update package versions
- remove reference to sort-by which had a vulnerability and is no longer maintained
- fixed jest tests

latest package versions

---

README.md

adding v1 note
